# fly.toml app configuration file generated for odin-facebook-resume-project on 2023-11-06T11:35:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "odin-facebook-resume-project"
primary_region = "lax"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

